# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec6f1c270ad2228f7c68f0e7cff5e693cd9a103acf1bb4f1b1ae985520bb6dc13ce74a26a94ef1c0ce418dacc4f10e6b8948b864469e2dac6362a8d107d4bdf3

test:
  secret_key_base: 541ca19ef60198309badcd8f326b6afc4b7b83f7d5e0accccc3a1f8d5b497cebc448cffc02ba2eb8bb572e7f7103d25f65154eb7af3e9ca3b538a6a24c3b06e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
